[telegram]
admin = "orsinium"
token = "..."

[redis]
addr = "localhost:6379"

[messages]
like = ["ğŸ’”", "â¤", "ğŸ§¡", "ğŸ’›", "ğŸ’š", "ğŸ’™", "ğŸ’œ", "ğŸ–¤", "ğŸ”¥"]
liked = "you â¤ï¸ it!"
disliked = "you got your ğŸ’” back"
self = "hey, stop liking yourself"
error = "Whoops... Something went wrong."
