[telegram]
admin = "orsinium"
token = "..."

[redis]
addr = "localhost:6379"

[messages]
like = ["â¤", "ğŸ§¡", "ğŸ’›", "ğŸ’š", "ğŸ’™", "ğŸ’œ", "ğŸ–¤"]
liked = "you â¤ï¸ it!"
disliked = "you got your ğŸ’” back"
error = "Whoops... Something went wrong."

